package org.hyperskill.academy.scala.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.ScalaGradleCourseCompatibilityProvider
import org.hyperskill.academy.learning.compatibility.ScalaSbtCourseCompatibilityProvider

class ScalaGradleCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(ScalaGradleCourseCompatibilityProvider::class)
class ScalaSbtCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(ScalaSbtCourseCompatibilityProvider::class)