package org.hyperskill.academy.rust.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.RsCourseCompatibilityProvider

class RsCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(RsCourseCompatibilityProvider::class)
