package org.hyperskill.academy.sql.jvm.gradle.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.SqlGradleCourseCompatibilityProvider

class SqlGradleCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(SqlGradleCourseCompatibilityProvider::class)
