package org.hyperskill.academy.learning.gradle

import org.hyperskill.academy.learning.courseFormat.BinaryContents
import org.hyperskill.academy.learning.courseFormat.EduFile
import org.hyperskill.academy.learning.courseFormat.InMemoryTextualContents
import org.hyperskill.academy.learning.courseFormat.InMemoryUndeterminedContents
import org.hyperskill.academy.learning.courseFormat.TextualContents
import org.jetbrains.annotations.VisibleForTesting

/**
 * Rewrites Gradle scripts of Hyperskill projects that the server still serves in a form the IDE cannot build.
 *
 * The scripts are course additional files, so the migration has to be applied in two places:
 * to the files as they arrive from the API (see `HyperskillConnector.loadAndFillAdditionalCourseInfo`),
 * which covers both project generation and course updates, and to the scripts already lying on disk of a project
 * generated by an older plugin version (see `GradleStartupActivity`).
 *
 * Both places must produce the same content: the course updater rewrites an additional file whenever the remote
 * content differs from the one on disk, so a migration applied only on disk is reverted on the next update check,
 * and, because the difference never goes away, on every check after it.
 */
object GradleScriptMigration {

  /**
   * Returns the migrated content of the Gradle script named [fileName], or [content] itself
   * if the file needs no migration.
   *
   * Every migration is idempotent, so it is safe to run on an already migrated script.
   */
  fun migrate(fileName: String, content: String): String = when (fileName) {
    GradleConstants.BUILD_GRADLE -> migrateLegacyUtilSourceSetReferences(content)
    GradleConstants.SETTINGS_GRADLE -> addToolchainResolver(content)
    else -> content
  }

  /**
   * Applies [migrate] to the Gradle scripts among [files] in place, leaving the other additional files untouched.
   */
  fun migrateAdditionalFiles(files: List<EduFile>) {
    for (file in files) {
      val contents = file.contents
      if (contents is BinaryContents) continue

      val originalText = contents.textualRepresentation
      val migratedText = migrate(file.name, originalText)
      if (migratedText == originalText) continue

      file.contents = if (contents is TextualContents) {
        InMemoryTextualContents(migratedText)
      }
      else {
        InMemoryUndeterminedContents(migratedText)
      }
    }
  }

  // The negative lookbehind also makes the replacement idempotent: an already migrated
  // `rootProject.project(':util')` is preceded by a dot and is not matched again
  private val LEGACY_UTIL_SOURCE_SET_REFERENCE =
    Regex("""(?<![\w.])project\((['"]):util\1\)\.sourceSets\.(?:main|test)\.output""")

  /**
   * Rewrites `project(':util').sourceSets.*.output` references left in build scripts of old projects.
   *
   * Inside a `dependencies { }` block such a call is resolved against `DependencyHandler`,
   * which since Gradle 9 provides its own `project(String)` returning a `ProjectDependency` instead of a `Project`,
   * so `sourceSets` is no longer resolvable there. Qualifying the call with `rootProject` makes it resolve
   * against `Project` again, which is valid for every Gradle version, so the migration is not tied to a
   * particular IDE or Gradle version.
   */
  @VisibleForTesting
  fun migrateLegacyUtilSourceSetReferences(content: String): String =
    content.replace(LEGACY_UTIL_SOURCE_SET_REFERENCE) { matchResult -> "rootProject.${matchResult.value}" }

  private const val FOOJAY_RESOLVER_ID = "org.gradle.toolchains.foojay-resolver-convention"
  private const val FOOJAY_RESOLVER_VERSION = "1.0.0"

  /** Matches the `hs-gradle-plugin` classpath entry that only Hyperskill settings scripts contain */
  private const val HS_GRADLE_PLUGIN = "hs-gradle-plugin"

  private val BUILD_SCRIPT_BLOCK_START = Regex("""(?m)^\s*buildscript\s*\{""")

  /** Leading blank line separates the inserted block from the `buildscript { }` block above it */
  private val TOOLCHAIN_RESOLVER_BLOCK = """
    |
    |
    |plugins {
    |  id '$FOOJAY_RESOLVER_ID' version '$FOOJAY_RESOLVER_VERSION'
    |}
  """.trimMargin()

  /**
   * Adds the Foojay toolchain resolver to `settings.gradle` of already generated Hyperskill projects.
   *
   * The generated build script requests a Java toolchain of `max(<Gradle daemon JVM>, hs.java.version)`.
   * Without a resolver Gradle cannot provision that JDK, so the build fails with
   * "Toolchain download repositories have not been configured" whenever it is not installed locally.
   *
   * Only scripts generated from the Hyperskill template are touched, and the resolver is inserted right after
   * the leading `buildscript { }` block because `plugins { }` may only be preceded by `buildscript { }`
   * and `pluginManagement { }`.
   */
  @VisibleForTesting
  fun addToolchainResolver(content: String): String {
    if (FOOJAY_RESOLVER_ID in content || HS_GRADLE_PLUGIN !in content) return content
    val insertionOffset = buildScriptBlockEndOffset(content) ?: return content
    return content.substring(0, insertionOffset) + TOOLCHAIN_RESOLVER_BLOCK + content.substring(insertionOffset)
  }

  /** Offset right after the closing brace of the leading `buildscript { }` block, or `null` if there is none */
  private fun buildScriptBlockEndOffset(content: String): Int? {
    val blockStart = BUILD_SCRIPT_BLOCK_START.find(content) ?: return null
    var depth = 0
    for (offset in blockStart.range.last..content.lastIndex) {
      when (content[offset]) {
        '{' -> depth++
        '}' -> if (--depth == 0) return offset + 1
      }
    }
    return null
  }
}
