package org.hyperskill.academy.kotlin.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.KtCourseCompatibilityProvider

class KtCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(KtCourseCompatibilityProvider::class)