package org.hyperskill.academy.shell.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.ShellCourseCompatibilityProvider

class ShellCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(ShellCourseCompatibilityProvider::class)