package org.hyperskill.academy.cpp.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase

class CppGTestCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(CppGTestCourseCompatibilityProvider::class)
class CppCatchCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(CppCatchCourseCompatibilityProvider::class)