package org.hyperskill.academy.jvm.gradle

import com.intellij.openapi.application.runWriteAction
import com.intellij.openapi.application.writeAction
import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.project.DumbService
import com.intellij.openapi.project.Project
import com.intellij.openapi.project.guessProjectDir
import com.intellij.openapi.startup.ProjectActivity
import com.intellij.openapi.vfs.VfsUtil
import com.intellij.openapi.vfs.VfsUtilCore
import kotlinx.coroutines.suspendCancellableCoroutine
import org.hyperskill.academy.jvm.gradle.generation.EduGradleUtils
import org.hyperskill.academy.jvm.gradle.generation.EduGradleUtils.setupGradleProject
import org.hyperskill.academy.jvm.gradle.generation.EduGradleUtils.updateGradleSettings
import org.hyperskill.academy.learning.EduUtilsKt.isEduProject
import org.hyperskill.academy.learning.RefreshCause
import org.hyperskill.academy.learning.StudyTaskManager
import org.hyperskill.academy.learning.courseFormat.hyperskill.HyperskillCourse
import org.hyperskill.academy.learning.gradle.GradleConstants
import org.hyperskill.academy.learning.gradle.GradleScriptMigration
import java.io.IOException
import kotlin.coroutines.resume

class GradleStartupActivity : ProjectActivity {

  override suspend fun execute(project: Project) {
    if (project.isDisposed || !project.isEduProject()) {
      return
    }
    if (EduGradleUtils.isConfiguredWithGradle(project)) {
      val buildScriptMigrated = migrateScript(project, GradleConstants.BUILD_GRADLE)
      val settingsMigrated = migrateScript(project, GradleConstants.SETTINGS_GRADLE)
      updateGradleSettings(project)
      if (buildScriptMigrated || settingsMigrated) {
        // The import triggered by project opening has already read the outdated script,
        // so it has to be re-run to pick up the migrated one.
        GradleCourseRefresher.firstAvailable()?.refresh(project, RefreshCause.DEPENDENCIES_UPDATED)
      }
    }

    // Convert DumbService.runWhenSmart to a suspending function
    suspendCancellableCoroutine { continuation ->
      DumbService.getInstance(project).runWhenSmart {
        val taskManager = StudyTaskManager.getInstance(project)
        val course = taskManager.course
        if (course == null) {
          LOG.warn("Opened project is with null course")
          continuation.resume(Unit)
          return@runWhenSmart
        }

        if (EduGradleUtils.isConfiguredWithGradle(project)) {
          setupGradleProject(project)
        }

        // Ensure util module directory exists for Hyperskill projects.
        // Gradle 9.x requires module directories to exist during project configuration.
        if (course is HyperskillCourse) {
          ensureUtilModuleDirectoryExists(project)
        }

        continuation.resume(Unit)
      }
    }
  }

  /**
   * Applies [GradleScriptMigration] to the Gradle script named [scriptName] in the project root.
   *
   * Only projects generated by an older plugin version need this: the scripts coming from the server are already
   * migrated by the time they are written to disk.
   *
   * @return `true` if the script was actually changed
   */
  private suspend fun migrateScript(project: Project, scriptName: String): Boolean {
    val projectDir = project.guessProjectDir() ?: return false
    val scriptFile = projectDir.findChild(scriptName) ?: return false
    if (scriptFile.isDirectory) return false

    return try {
      val originalContent = VfsUtilCore.loadText(scriptFile)
      val migratedContent = GradleScriptMigration.migrate(scriptName, originalContent)
      if (migratedContent == originalContent) return false

      writeAction {
        VfsUtil.saveText(scriptFile, migratedContent)
      }
      LOG.info("Migrated ${scriptFile.path}")
      true
    }
    catch (e: IOException) {
      LOG.warn("Failed to migrate ${scriptFile.path}", e)
      false
    }
  }

  private fun ensureUtilModuleDirectoryExists(project: Project) {
    val projectDir = project.guessProjectDir() ?: return
    val utilDir = projectDir.findChild(UTIL_MODULE_NAME)
    if (utilDir != null && utilDir.isDirectory) return

    runWriteAction {
      VfsUtil.createDirectoryIfMissing(projectDir, "$UTIL_MODULE_NAME/src")
    }
  }

  companion object {
    private val LOG = Logger.getInstance(GradleStartupActivity::class.java)

    private const val UTIL_MODULE_NAME = "util"
  }
}
