package org.hyperskill.academy.go.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.GoCourseCompatibilityProvider

class GoCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(GoCourseCompatibilityProvider::class)