package org.hyperskill.academy.javascript.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.JsCourseCompatibilityProvider

class JsCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(JsCourseCompatibilityProvider::class)