package org.hyperskill.academy.java.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.JCourseCompatibilityProvider

class JCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(JCourseCompatibilityProvider::class)