package org.hyperskill.academy.python.compatibility

import org.hyperskill.academy.learning.compatibility.CourseCompatibilityProviderTestBase
import org.hyperskill.academy.learning.compatibility.PyCourseCompatibilityProvider

class PyCourseCompatibilityProviderTest : CourseCompatibilityProviderTestBase(PyCourseCompatibilityProvider::class)
